#!/usr/bin/env bash

set -eo pipefail

if [ ! -f pubspec.yaml ]; then
  echo 'Initializing ClojureDart project'
  clojure -M:cljd init
fi

echo 'Running ClojureDart tests'
clojure -M:cljd test edamame.core-test "$@"
