# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  jvm:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.11.1.1113.sh
            chmod +x linux-install-1.11.1.1113.sh
            sudo ./linux-install-1.11.1.1113.sh
      - run:
          name: Run JVM tests
          command: |
            script/test/jvm
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
  node:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.8.1-node
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Clojure
          command: |
            wget -nc https://download.clojure.org/install/linux-install-1.11.1.1113.sh
            chmod +x linux-install-1.11.1.1113.sh
            sudo ./linux-install-1.11.1.1113.sh
      - run:
          name: Run Node tests
          command: |
            script/test/node
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
  deploy:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: .circleci/script/deploy
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
workflows:
  version: 2
  ci:
    jobs:
      - jvm
      - node
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - jvm
            - node
      # - docker:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - jvm
      #       - linux
      #       - mac
